services:
  tandoor:
    restart: unless-stopped
    image: vabene1111/recipes
    networks:
      - tandoor
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - mediafiles:/opt/recipes/mediafiles
    environment:
      SECRET_KEY: ${SECRET_KEY}
      TZ: Asia/Tokyo
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_ENGINE: django.db.backends.postgresql
      POSTGRES_HOST: postgre_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  staticfiles:
  mediafiles:

networks:
  tandoor:
    external: true
